theme: jekyll-theme-slate

sections:
  brief_bio :
    enabled : true
    image :
      enabled : false
      url : false
    content :
      enabled : true
    social_links :
      enabled : false
    github_projects :
      enabled : true
  social_links :
    enabled : false
  github_projects :
    enabled : false
  external_links :
    enabled : true
  archive :
    enabled : false
  categories :
    enabled : false
  tags :
    enabled : false

navbar :
  archive :
    enabled : true
  categories :
    enabled : true
  tags :
    enabled : true
  github_projects :
    enabled : false
  social_links :
    enabled : false
  external_links :
    enabled : false

github_projects :
  header : newsched
  projects :
  - project :
    name : newsched
    url : https://github.com/gnuradio/newsched