from newsched import gr

class pytest_numpy(gr.sync_block):
    ## This should be able to be autogenerated
    def __init__(self, *args, **kwargs):
        gr.sync_block.__init__(
            self,
            name="pytest")

        self.itemsize = kwargs['itemsize'] if 'itemsize' in kwargs else 0
            
        self.add_port(gr.untyped_port("in", gr.INPUT, self.itemsize))
        self.add_port(gr.untyped_port("out", gr.OUTPUT, self.itemsize))

    ## Move this into a separate file
    def work(self, inputs, outputs):
        noutput_items = outputs[0].n_items
        print(noutput_items)
        outputs[0].produce(noutput_items)
        ninput_items = inputs[0].n_items
        print(ninput_items)

        inbuf = self.get_input_array(inputs, 0)
        outbuf = self.get_output_array(outputs, 0)

        outbuf[:] = inbuf

        return gr.work_return_t.WORK_OK