# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnuradio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gnuradio.proto',
  package='gnuradio',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0egnuradio.proto\x12\x08gnuradio\"9\n\x16\x46lowgraphCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tsecondary\x18\x02 \x01(\x08\"&\n\x16\x46lowgraphActionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xfb\x01\n\x1d\x46lowgraphConnectBlocksRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tsrc_block\x18\x02 \x01(\t\x12\x17\n\rsrc_port_name\x18\x03 \x01(\tH\x00\x12\x18\n\x0esrc_port_index\x18\x04 \x01(\x05H\x00\x12\x12\n\ndest_block\x18\x05 \x01(\t\x12\x18\n\x0e\x64\x65st_port_name\x18\x06 \x01(\tH\x01\x12\x19\n\x0f\x64\x65st_port_index\x18\x07 \x01(\x05H\x01\x12\x16\n\tedge_name\x18\x08 \x01(\tH\x02\x88\x01\x01\x42\n\n\x08src_portB\x0b\n\tdest_portB\x0c\n\n_edge_name\"R\n\x1b\x46lowgraphConnectBlocksReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\x12\x11\n\tedge_name\x18\x03 \x01(\t\"U\n\x12\x42lockCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06module\x18\x02 \x01(\t\x12\r\n\x05\x62lock\x18\x03 \x01(\t\x12\x12\n\nparameters\x18\x04 \x01(\t\"F\n\x12\x42lockMethodRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\t\"0\n\x0cGenericReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2\xeb\x03\n\x08GNURadio\x12M\n\x0f\x43reateFlowgraph\x12 .gnuradio.FlowgraphCreateRequest\x1a\x16.gnuradio.GenericReply\"\x00\x12\x45\n\x0b\x43reateBlock\x12\x1c.gnuradio.BlockCreateRequest\x1a\x16.gnuradio.GenericReply\"\x00\x12\x61\n\rConnectBlocks\x12\'.gnuradio.FlowgraphConnectBlocksRequest\x1a%.gnuradio.FlowgraphConnectBlocksReply\"\x00\x12L\n\x0eStartFlowgraph\x12 .gnuradio.FlowgraphActionRequest\x1a\x16.gnuradio.GenericReply\"\x00\x12K\n\rStopFlowgraph\x12 .gnuradio.FlowgraphActionRequest\x1a\x16.gnuradio.GenericReply\"\x00\x12K\n\rWaitFlowgraph\x12 .gnuradio.FlowgraphActionRequest\x1a\x16.gnuradio.GenericReply\"\x00\x62\x06proto3'
)




_FLOWGRAPHCREATEREQUEST = _descriptor.Descriptor(
  name='FlowgraphCreateRequest',
  full_name='gnuradio.FlowgraphCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gnuradio.FlowgraphCreateRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secondary', full_name='gnuradio.FlowgraphCreateRequest.secondary', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=85,
)


_FLOWGRAPHACTIONREQUEST = _descriptor.Descriptor(
  name='FlowgraphActionRequest',
  full_name='gnuradio.FlowgraphActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gnuradio.FlowgraphActionRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=125,
)


_FLOWGRAPHCONNECTBLOCKSREQUEST = _descriptor.Descriptor(
  name='FlowgraphConnectBlocksRequest',
  full_name='gnuradio.FlowgraphConnectBlocksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gnuradio.FlowgraphConnectBlocksRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_block', full_name='gnuradio.FlowgraphConnectBlocksRequest.src_block', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_port_name', full_name='gnuradio.FlowgraphConnectBlocksRequest.src_port_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_port_index', full_name='gnuradio.FlowgraphConnectBlocksRequest.src_port_index', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dest_block', full_name='gnuradio.FlowgraphConnectBlocksRequest.dest_block', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dest_port_name', full_name='gnuradio.FlowgraphConnectBlocksRequest.dest_port_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dest_port_index', full_name='gnuradio.FlowgraphConnectBlocksRequest.dest_port_index', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_name', full_name='gnuradio.FlowgraphConnectBlocksRequest.edge_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='src_port', full_name='gnuradio.FlowgraphConnectBlocksRequest.src_port',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='dest_port', full_name='gnuradio.FlowgraphConnectBlocksRequest.dest_port',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_edge_name', full_name='gnuradio.FlowgraphConnectBlocksRequest._edge_name',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=128,
  serialized_end=379,
)


_FLOWGRAPHCONNECTBLOCKSREPLY = _descriptor.Descriptor(
  name='FlowgraphConnectBlocksReply',
  full_name='gnuradio.FlowgraphConnectBlocksReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='gnuradio.FlowgraphConnectBlocksReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='gnuradio.FlowgraphConnectBlocksReply.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_name', full_name='gnuradio.FlowgraphConnectBlocksReply.edge_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=463,
)


_BLOCKCREATEREQUEST = _descriptor.Descriptor(
  name='BlockCreateRequest',
  full_name='gnuradio.BlockCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gnuradio.BlockCreateRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='module', full_name='gnuradio.BlockCreateRequest.module', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block', full_name='gnuradio.BlockCreateRequest.block', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='gnuradio.BlockCreateRequest.parameters', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=550,
)


_BLOCKMETHODREQUEST = _descriptor.Descriptor(
  name='BlockMethodRequest',
  full_name='gnuradio.BlockMethodRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gnuradio.BlockMethodRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='gnuradio.BlockMethodRequest.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='gnuradio.BlockMethodRequest.parameters', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=622,
)


_GENERICREPLY = _descriptor.Descriptor(
  name='GenericReply',
  full_name='gnuradio.GenericReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='gnuradio.GenericReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='gnuradio.GenericReply.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=624,
  serialized_end=672,
)

_FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['src_port'].fields.append(
  _FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['src_port_name'])
_FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['src_port_name'].containing_oneof = _FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['src_port']
_FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['src_port'].fields.append(
  _FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['src_port_index'])
_FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['src_port_index'].containing_oneof = _FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['src_port']
_FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['dest_port'].fields.append(
  _FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['dest_port_name'])
_FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['dest_port_name'].containing_oneof = _FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['dest_port']
_FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['dest_port'].fields.append(
  _FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['dest_port_index'])
_FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['dest_port_index'].containing_oneof = _FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['dest_port']
_FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['_edge_name'].fields.append(
  _FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['edge_name'])
_FLOWGRAPHCONNECTBLOCKSREQUEST.fields_by_name['edge_name'].containing_oneof = _FLOWGRAPHCONNECTBLOCKSREQUEST.oneofs_by_name['_edge_name']
DESCRIPTOR.message_types_by_name['FlowgraphCreateRequest'] = _FLOWGRAPHCREATEREQUEST
DESCRIPTOR.message_types_by_name['FlowgraphActionRequest'] = _FLOWGRAPHACTIONREQUEST
DESCRIPTOR.message_types_by_name['FlowgraphConnectBlocksRequest'] = _FLOWGRAPHCONNECTBLOCKSREQUEST
DESCRIPTOR.message_types_by_name['FlowgraphConnectBlocksReply'] = _FLOWGRAPHCONNECTBLOCKSREPLY
DESCRIPTOR.message_types_by_name['BlockCreateRequest'] = _BLOCKCREATEREQUEST
DESCRIPTOR.message_types_by_name['BlockMethodRequest'] = _BLOCKMETHODREQUEST
DESCRIPTOR.message_types_by_name['GenericReply'] = _GENERICREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlowgraphCreateRequest = _reflection.GeneratedProtocolMessageType('FlowgraphCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _FLOWGRAPHCREATEREQUEST,
  '__module__' : 'gnuradio_pb2'
  # @@protoc_insertion_point(class_scope:gnuradio.FlowgraphCreateRequest)
  })
_sym_db.RegisterMessage(FlowgraphCreateRequest)

FlowgraphActionRequest = _reflection.GeneratedProtocolMessageType('FlowgraphActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FLOWGRAPHACTIONREQUEST,
  '__module__' : 'gnuradio_pb2'
  # @@protoc_insertion_point(class_scope:gnuradio.FlowgraphActionRequest)
  })
_sym_db.RegisterMessage(FlowgraphActionRequest)

FlowgraphConnectBlocksRequest = _reflection.GeneratedProtocolMessageType('FlowgraphConnectBlocksRequest', (_message.Message,), {
  'DESCRIPTOR' : _FLOWGRAPHCONNECTBLOCKSREQUEST,
  '__module__' : 'gnuradio_pb2'
  # @@protoc_insertion_point(class_scope:gnuradio.FlowgraphConnectBlocksRequest)
  })
_sym_db.RegisterMessage(FlowgraphConnectBlocksRequest)

FlowgraphConnectBlocksReply = _reflection.GeneratedProtocolMessageType('FlowgraphConnectBlocksReply', (_message.Message,), {
  'DESCRIPTOR' : _FLOWGRAPHCONNECTBLOCKSREPLY,
  '__module__' : 'gnuradio_pb2'
  # @@protoc_insertion_point(class_scope:gnuradio.FlowgraphConnectBlocksReply)
  })
_sym_db.RegisterMessage(FlowgraphConnectBlocksReply)

BlockCreateRequest = _reflection.GeneratedProtocolMessageType('BlockCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKCREATEREQUEST,
  '__module__' : 'gnuradio_pb2'
  # @@protoc_insertion_point(class_scope:gnuradio.BlockCreateRequest)
  })
_sym_db.RegisterMessage(BlockCreateRequest)

BlockMethodRequest = _reflection.GeneratedProtocolMessageType('BlockMethodRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKMETHODREQUEST,
  '__module__' : 'gnuradio_pb2'
  # @@protoc_insertion_point(class_scope:gnuradio.BlockMethodRequest)
  })
_sym_db.RegisterMessage(BlockMethodRequest)

GenericReply = _reflection.GeneratedProtocolMessageType('GenericReply', (_message.Message,), {
  'DESCRIPTOR' : _GENERICREPLY,
  '__module__' : 'gnuradio_pb2'
  # @@protoc_insertion_point(class_scope:gnuradio.GenericReply)
  })
_sym_db.RegisterMessage(GenericReply)



_GNURADIO = _descriptor.ServiceDescriptor(
  name='GNURadio',
  full_name='gnuradio.GNURadio',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=675,
  serialized_end=1166,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateFlowgraph',
    full_name='gnuradio.GNURadio.CreateFlowgraph',
    index=0,
    containing_service=None,
    input_type=_FLOWGRAPHCREATEREQUEST,
    output_type=_GENERICREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateBlock',
    full_name='gnuradio.GNURadio.CreateBlock',
    index=1,
    containing_service=None,
    input_type=_BLOCKCREATEREQUEST,
    output_type=_GENERICREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectBlocks',
    full_name='gnuradio.GNURadio.ConnectBlocks',
    index=2,
    containing_service=None,
    input_type=_FLOWGRAPHCONNECTBLOCKSREQUEST,
    output_type=_FLOWGRAPHCONNECTBLOCKSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartFlowgraph',
    full_name='gnuradio.GNURadio.StartFlowgraph',
    index=3,
    containing_service=None,
    input_type=_FLOWGRAPHACTIONREQUEST,
    output_type=_GENERICREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopFlowgraph',
    full_name='gnuradio.GNURadio.StopFlowgraph',
    index=4,
    containing_service=None,
    input_type=_FLOWGRAPHACTIONREQUEST,
    output_type=_GENERICREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WaitFlowgraph',
    full_name='gnuradio.GNURadio.WaitFlowgraph',
    index=5,
    containing_service=None,
    input_type=_FLOWGRAPHACTIONREQUEST,
    output_type=_GENERICREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GNURADIO)

DESCRIPTOR.services_by_name['GNURadio'] = _GNURADIO

# @@protoc_insertion_point(module_scope)
