name: build and run tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - run: sudo apt-get update && sudo apt-get install -yq libboost-dev libboost-program-options-dev libzmq3-dev doxygen libspdlog-dev libyaml-cpp-dev libgtest-dev libfmt-dev wget
      - run: pip install meson ninja mako six
      - name: build_volk
        run: mkdir -p volk && curl -Lo volk.tar.gz https://github.com/gnuradio/volk/archive/v2.2.1.tar.gz && tar xzf volk.tar.gz -C volk --strip-components=1 && cmake -DCMAKE_BUILD_TYPE=Release -S ./volk/ -B build && cd build && cmake --build . && sudo cmake --build . --target install && cd ../ && rm -rf build
      - name: build_flatc
        # run: mkdir -p fb && curl -Lo fb.tar.gz https://github.com/google/flatbuffers/archive/v1.12.0.tar.gz && tar xzf fb.tar.gz -C fb --strip-components=1 && cmake -DCMAKE_BUILD_TYPE=Release -S ./fb/ -B build && cd build && cmake --build . && sudo cmake --build . --target install && cd ../ && rm -rf build
        run: git clone https://github.com/google/flatbuffers.git && cd flatbuffers && git checkout aafc5dc9500f01c64 && mkdir build && cd build && cmake ../ && make install -j 
      - run: meson setup build --buildtype=debugoptimized -Denable_testing=true
        env:
          CC: gcc
      - run: meson test -C build -v
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Linux_Meson_Testlog
          path: build/meson-logs/testlog.txt
