name: build and run tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  # build:
  # runs-on: ubuntu-20.04
  # steps:
  #   - uses: actions/checkout@v2
  #   # install dependencies
  #   - name: dependencies
  #     run: sudo apt-get update && sudo apt-get install -yq libboost-dev libboost-program-options-dev libzmq3-dev python3-mako doxygen libspdlog-dev libyaml-cpp-dev python3-pip && pip3 install meson
  #   # build volk
  #   - name: build_volk
  #     run: mkdir -p volk && curl -Lo volk.tar.gz https://github.com/gnuradio/volk/archive/v2.1.0.tar.gz && tar xzf volk.tar.gz -C volk --strip-components=1 && cmake -DCMAKE_BUILD_TYPE=Release -S ./volk/ -B build && cd build && cmake --build . && sudo cmake --build . --target install && cd ../ && rm -rf build
  #   # setup newsched
  #   - name: setup and compile
  #     run: meson setup build --buildtype=debugoptimized -Denable_testing=true && meson compile -C build
  #   # run tests
  #   - name: test
  #     run: meson test -C build

  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - run: sudo apt-get update && sudo apt-get install -yq libboost-dev libboost-program-options-dev libzmq3-dev doxygen libspdlog-dev libyaml-cpp-dev libgtest-dev
      - run: pip install meson ninja mako six
      - name: build_volk
        run: mkdir -p volk && curl -Lo volk.tar.gz https://github.com/gnuradio/volk/archive/v2.2.1.tar.gz && tar xzf volk.tar.gz -C volk --strip-components=1 && cmake -DCMAKE_BUILD_TYPE=Release -S ./volk/ -B build && cd build && cmake --build . && sudo cmake --build . --target install && cd ../ && rm -rf build
      - run: meson setup build --buildtype=debugoptimized -Denable_testing=true
        env:
          CC: gcc
      - run: meson test -C build -v
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Linux_Meson_Testlog
          path: build/meson-logs/testlog.txt
