name: build and run tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  linux-docker:
  # All of these shall depend on the formatting check (needs: check-formatting)
    runs-on: ubuntu-20.04
    # The GH default is 360 minutes (it's also the max as of Feb-2021). However
    # we should fail sooner. The only reason to exceed this time is if a test
    # hangs.
    timeout-minutes: 120
    strategy:
      # Enabling fail-fast would kill all Dockers if one of them fails. We want
      # maximum output.
      fail-fast: false
      matrix:
        # For every distro we want to test here, add one key 'distro' with a
        # descriptive name, and one key 'containerid' with the name of the
        # container (i.e., what you want to docker-pull)
        include:
          - distro: 'Ubuntu 20.04'
            containerid: 'mormj/newsched-ci-docker:ubuntu-20.04'
            cxxflags: -Werror
          - distro: 'Ubuntu 22.04'
            containerid: 'mormj/newsched-ci-docker:ubuntu-22.04'
            cxxflags: -Werror
          - distro: 'Fedora 34'
            containerid: 'mormj/newsched-ci-docker:fedora-34'
            cxxflags: ''
          # - distro: 'CentOS 8.3'
          #   containerid: 'gnuradio/ci:centos-8.3-3.9'
          #   cxxflags: -Werror
          # - distro: 'Debian 10'
          #   containerid: 'gnuradio/ci-debian-10-3.9:1.0'
          #   cxxflags: -Werror
    name: ${{ matrix.distro }}
    container:
      image: ${{ matrix.containerid }}
      volumes:
        - build_data:/build
      options: --cpus 2
    steps:
    - uses: actions/checkout@v2
      name: Checkout Project
    - name: Meson Setup
      run: 'cd ${GITHUB_WORKSPACE} && meson setup build --buildtype=debugoptimized -Denable_testing=true' 
    - name: Make
      run: 'cd ${GITHUB_WORKSPACE}/build && ninja'
    - name: Make Test
      run: 'cd ${GITHUB_WORKSPACE}/build && ninja test'
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
