name: build and run tests
on:
  push:
    branches: [ modular, master ]
  pull_request:
    branches: [ modular, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -yq libboost-dev libzmq3-dev python3-mako doxygen
    # build volk
    - name: build_volk
      run: mkdir -p volk && curl -Lo volk.tar.gz https://github.com/gnuradio/volk/archive/v2.1.0.tar.gz && tar xzf volk.tar.gz -C volk --strip-components=1 && cmake -DCMAKE_BUILD_TYPE=Release -S ./volk/ -B build && cd build && cmake --build . && sudo cmake --build . --target install && cd ../ && rm -rf build
    # build project
    - name: mkdir
      run: mkdir build 
    - name: cmake
      working-directory: build
      run: cmake ..
    - name: cmake make
      working-directory: build
      run: make -j
    # run tests
    - name: run tests
      working-directory: build
      run: make test
